#!/bin/sh
# Copyright (C) 2021 Aleksander Morgado <aleksander@aleksander.es>

# Load hotplug common utilities
. /usr/share/ModemManager/modemmanager.common

# We require a device name
[ -n "$DEVNAME" ] || exit

# Always make sure the rundir exists
mkdir -m 0755 -p "${MODEMMANAGER_RUNDIR}"

# Report rpmsg
mm_log "${ACTION} rpmsg control port ${DEVNAME}: event processed"
mm_report_event "${ACTION}" "${DEVNAME}" "rpmsg" "/sys${DEVPATH}"
